#!/bin/bash

inotifywait -mr  --timefmt '%d/%m/%y %H:%M' --format '%w%f' -e create -e moved_to /mnt | while read file; do

 FILECHANGE="${file}"
 date=$(date +"%d/%m/%y")
 time=$(date +"%H:%M")

 if  file -i "$FILECHANGE" | grep -q video; then
    nice /home/simenhg/github/media_server_scripts/corruptedFilesWatcher/delete-corrupted-video-files.py -D -i "$FILECHANGE"
    echo "At ${time} on ${date}, file $FILECHANGE was checked for damage."
fi
done
